name: Back to Source Repos

on:
  push:
    branches:
      - version-16

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hub
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync Frappe
        env:
          GH_TOKEN: ${{ secrets.HUB_TRANSLATIONS_TOKEN }}
        run: |
          if [ -f "frappe/locale/es.po" ]; then
            git clone https://$GH_TOKEN@github.com/edalca/frappe.git frappe_repo
            cd frappe_repo
            # Cambiamos a la rama l10n_version-16 directamente
            git checkout l10n_version-16 || git checkout -b l10n_version-16
            
            cp ../frappe/locale/es.po frappe/locale/es.po
            git add .
            if git commit -m "chore: update spanish translations from hub"; then
              git push origin l10n_version-16
              # Abre el PR de l10n_version-16 hacia version-16 si no existe uno
              gh pr create --title "Translate: Spanish update (l10n)" --body "Automatic sync from hub" --base version-16 --head l10n_version-16 || echo "PR already exists"
            fi
            cd ..
          fi

      - name: Sync HRMS
        env:
          GH_TOKEN: ${{ secrets.HUB_TRANSLATIONS_TOKEN }}
        run: |
          if [ -f "hrms/locale/es.po" ]; then
            git clone https://$GH_TOKEN@github.com/edalca/hrms.git hrms_repo
            cd hrms_repo
            git checkout l10n_version-16 || git checkout -b l10n_version-16
            
            cp ../hrms/locale/es.po hrms/locale/es.po
            git add .
            if git commit -m "chore: update spanish translations from hub"; then
              git push origin l10n_version-16
              gh pr create --title "Translate: HRMS Spanish update (l10n)" --body "Automatic sync from hub" --base version-16 --head l10n_version-16 || echo "PR already exists"
            fi
            cd ..
          fi