name: Back to Source Repos

on:
  push:
    branches:
      - version-16

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hub
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync Frappe
        env:
          GH_TOKEN: ${{ secrets.HUB_TRANSLATIONS_TOKEN }}
        run: |
          if [ -f "frappe/locale/es.po" ]; then
            git clone https://$GH_TOKEN@github.com/edalca/frappe.git frappe_repo
            cd frappe_repo
            git checkout version-16
            git checkout -b translations-update-$(date +%s)
            # Copiamos el archivo DESPUÉS del checkout para evitar conflictos
            cp ../frappe/locale/es.po frappe/locale/es.po
            git add .
            if git commit -m "chore: update spanish translations from hub"; then
              git push origin translations-update-$(date +%s)
              gh pr create --title "Translate: Spanish update from Hub" --body "Automatic sync" --base version-16
            fi
            cd ..
          fi

      - name: Sync HRMS
        env:
          GH_TOKEN: ${{ secrets.HUB_TRANSLATIONS_TOKEN }}
        run: |
          if [ -f "hrms/locale/es.po" ]; then
            git clone https://$GH_TOKEN@github.com/edalca/hrms.git hrms_repo
            cd hrms_repo
            git checkout version-16
            git checkout -b hrms-trans-update-$(date +%s)
            # Copiamos el archivo DESPUÉS del checkout
            cp ../hrms/locale/es.po hrms/locale/es.po
            git add .
            if git commit -m "chore: update spanish translations from hub"; then
              git push origin hrms-trans-update-$(date +%s)
              gh pr create --title "Translate: HRMS Spanish update from Hub" --body "Automatic sync" --base version-16
            fi
            cd ..
          fi